### ISSUE TITLE
Please enable issues on `vscode-mapcss-syntax`

### ISSUE THREAD

**Issue by awebeer256** [whubsch/custom-josm-rules#1]
I wanted to open an issue on [`vscode-mapcss-syntax`](https://github.com/whubsch/vscode-mapcss-syntax), but issues are currently turned off for that repo, so opening this issue instead was the best thing I could think of :shrug:. Please turn them on over there.

**Comment by whubsch** [comment]
Should be fixed now. Pull requests are welcome!
